CREATE OR REPLACE OPERATOR "C##METEO"."METEO_LESSTHAN_TWO_PARAM_SPEC" BINDING
	("C##METEO"."METEO_T", NUMBER, NUMBER, VARCHAR2, NUMBER, VARCHAR2, NUMBER, TIMESTAMP, TIMESTAMP) RETURN NUMBER
	   USING "METEO_LESSTHAN_TWO_PARAMETERS_SPECIFIC_FUNC";
