CREATE OR REPLACE OPERATOR "C##METEO"."METEO_GREATERTHAN_ONE_PARAM_SPEC" BINDING
	("C##METEO"."METEO_T", NUMBER, NUMBER, NUMBER, VARCHAR2, TIMESTAMP, TIMESTAMP) RETURN NUMBER
	   USING "METEO_GREATERTHAN_ONE_PARAMETER_SPECIFIC_FUNC";
