CREATE OR REPLACE OPERATOR "C##METEO"."METEO_LESSTHAN_ONE_PARAM_SPEC" BINDING
	("C##METEO"."METEO_T", NUMBER, NUMBER, NUMBER, VARCHAR2, TIMESTAMP, TIMESTAMP) RETURN NUMBER
	   USING "METEO_LESSTHAN_ONE_PARAMETER_SPECIFIC_FUNC";
