CREATE OR REPLACE OPERATOR "C##METEO"."METEO_EQUALS_TWO_PARAM_ANY" BINDING
	("C##METEO"."METEO_T", VARCHAR2, NUMBER, VARCHAR2, NUMBER, TIMESTAMP, TIMESTAMP) RETURN NUMBER
	   USING "METEO_EQUALS_TWO_PARAMETERS_ANY_FUNC";
