create indextype meteo_idxtype
FOR
    METEO_EQUALS_ONE_PARAM_ANY(METEO_T, NUMBER, VARCHAR2, TIMESTAMP, TIMESTAMP)
    ,METEO_EQUALS_ONE_PARAM_SPEC(METEO_T, NUMBER, NUMBER, NUMBER, VARCHAR2, TIMESTAMP, TIMESTAMP)
    ,METEO_EQUALS_TWO_PARAM_ANY(METEO_T, VARCHAR2, NUMBER, VARCHAR2, NUMBER, TIMESTAMP, TIMESTAMP)
    ,METEO_EQUALS_TWO_PARAM_SPEC(METEO_T, NUMBER, NUMBER, VARCHAR2, NUMBER, VARCHAR2, NUMBER, TIMESTAMP, TIMESTAMP)
    ,METEO_GREATERTHAN_ONE_PARAM_ANY(METEO_T, NUMBER, VARCHAR2, TIMESTAMP, TIMESTAMP)
    ,METEO_GREATERTHAN_ONE_PARAM_SPEC(METEO_T, NUMBER, NUMBER, NUMBER, VARCHAR2, TIMESTAMP, TIMESTAMP)
    ,METEO_GREATERTHAN_TWO_PARAM_ANY(METEO_T, VARCHAR2, NUMBER, VARCHAR2, NUMBER, TIMESTAMP, TIMESTAMP)
    ,METEO_GREATERTHAN_TWO_PARAM_SPEC(METEO_T, NUMBER, NUMBER, VARCHAR2, NUMBER, VARCHAR2, NUMBER, TIMESTAMP, TIMESTAMP)
    ,METEO_LESSTHAN_ONE_PARAM_ANY(METEO_T, NUMBER, VARCHAR2, TIMESTAMP, TIMESTAMP)
    ,METEO_LESSTHAN_ONE_PARAM_SPEC(METEO_T, NUMBER, NUMBER, NUMBER, VARCHAR2, TIMESTAMP, TIMESTAMP)
    ,METEO_LESSTHAN_TWO_PARAM_ANY(METEO_T, VARCHAR2, NUMBER, VARCHAR2, NUMBER, TIMESTAMP, TIMESTAMP)
    ,METEO_LESSTHAN_TWO_PARAM_SPEC(METEO_T, NUMBER, NUMBER, VARCHAR2, NUMBER, VARCHAR2, NUMBER, TIMESTAMP, TIMESTAMP)
USING meteo_idxtype_im
    