CREATE OR REPLACE OPERATOR "C##METEO"."METEO_BETTER_CONDITION_DIFFREADINGS" BINDING
	("C##METEO"."METEO_T", "C##METEO"."METEO_T", NUMBER, NUMBER) RETURN NUMBER
	   USING "METEO_BETTER_CONDITION_SAMEZONES_DIFFREADINGS_FUNC";
